[platformio]
src_dir = .

[env:esp32]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
build_type = debug
debug_build_flags = -Og -ggdb3 -g3

build_src_filter = +<*.ino> +<*.cpp> +<*.c>
